export const metadata = {
  title: 'Colorize AI',
  description: 'Generated by Darsh',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" type="image/png" sizes="any" href="/big.png"/>
      <body>{children}</body>
    </html>
  );
}